-- Create the contact_messages table
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text,
  message text not null,
  status text default 'unread' check (status in ('unread', 'read', 'replied'))
);

-- Enable Row Level Security
alter table public.contact_messages enable row level security;

-- Policy 1: Allow anyone (anon + authenticated) to insert messages (Contact Form)
-- This allows guests to send messages without logging in
create policy "Allow public to insert messages"
  on public.contact_messages
  for insert
  to public
  with check (true);

-- Policy 2: Allow admins to view all messages
-- This relies on your existing is_admin function
create policy "Allow admins to view messages"
  on public.contact_messages
  for select
  to authenticated
  using ( is_admin(auth.uid()) );

-- Policy 3: Allow admins to update messages (e.g. Mark as read)
create policy "Allow admins to update messages"
  on public.contact_messages
  for update
  to authenticated
  using ( is_admin(auth.uid()) );

-- Policy 4: Allow admins to delete messages
create policy "Allow admins to delete messages"
  on public.contact_messages
  for delete
  to authenticated
  using ( is_admin(auth.uid()) );
