-- 1. SETUP PUBLIC PROFILES & ADMIN FUNCTION (Must run first)
-- Ensure profiles table has a role column
alter table public.profiles add column if not exists role text default 'user';

-- Create is_admin function (SECURE VERSION)
create or replace function public.is_admin(user_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  user_role text;
begin
  select role into user_role from public.profiles where id = user_id;
  return user_role = 'admin';
end;
$$;


-- 2. SETUP CONTACT MESSAGES
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text,
  message text not null,
  status text default 'unread' check (status in ('unread', 'read', 'replied'))
);
alter table public.contact_messages enable row level security;

-- Drop policies to avoid errors on re-run
drop policy if exists "Allow public to insert messages" on public.contact_messages;
drop policy if exists "Allow admins to view messages" on public.contact_messages;
drop policy if exists "Allow admins to update messages" on public.contact_messages;
drop policy if exists "Allow admins to delete messages" on public.contact_messages;

create policy "Allow public to insert messages" on public.contact_messages for insert to public with check (true);
create policy "Allow admins to view messages" on public.contact_messages for select to authenticated using ( is_admin(auth.uid()) );
create policy "Allow admins to update messages" on public.contact_messages for update to authenticated using ( is_admin(auth.uid()) );
create policy "Allow admins to delete messages" on public.contact_messages for delete to authenticated using ( is_admin(auth.uid()) );


-- 3. SETUP TESTIMONIALS
create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  content text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  location text not null,
  source text default 'google' check (source in ('google', 'tripadvisor')),
  visible boolean default true,
  avatar_url text
);

-- FIX: Ensure columns exist if table already existed without them
alter table public.testimonials add column if not exists source text default 'google' check (source in ('google', 'tripadvisor'));
alter table public.testimonials add column if not exists visible boolean default true;
alter table public.testimonials add column if not exists avatar_url text;
alter table public.testimonials add column if not exists updated_at timestamp with time zone default timezone('utc'::text, now());

alter table public.testimonials enable row level security;

drop policy if exists "Allow public to read visible testimonials" on public.testimonials;
drop policy if exists "Allow admins to manage testimonials" on public.testimonials;

create policy "Allow public to read visible testimonials" on public.testimonials for select to public using (visible = true);
create policy "Allow admins to manage testimonials" on public.testimonials for all to authenticated using ( is_admin(auth.uid()) ) with check ( is_admin(auth.uid()) );


-- 4. INSERT DUMMY DATA (Optional)
insert into public.testimonials (name, content, rating, location, source, visible)
values 
('Michael Scott', 'The trip to Maasai Mara was absolutely breathtaking. We saw lions within the first hour!', 5, 'USA', 'google', true),
('Sarah Jenkins', 'Professional, safe, and truly spectacular service. Highly recommended.', 5, 'UK', 'tripadvisor', true)
-- Only insert if table is empty to avoid duplicates on re-runs (simple check workaround)
on conflict do nothing;
