-- Create the testimonials table
create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  content text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  location text not null,
  source text default 'google' check (source in ('google', 'tripadvisor')),
  visible boolean default true,
  avatar_url text -- optional
);

-- Enable Row Level Security
alter table public.testimonials enable row level security;

-- Policy 1: Allow public to read visible testimonials
create policy "Allow public to read visible testimonials"
  on public.testimonials
  for select
  to public
  using (visible = true);

-- Policy 2: Allow admins to do everything
create policy "Allow admins to manage testimonials"
  on public.testimonials
  for all
  to authenticated
  using ( is_admin(auth.uid()) )
  with check ( is_admin(auth.uid()) );
